spring:
  kafka:
    bootstrap-servers: cbq-hackathon.servicebus.windows.net:9093
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: UvenuliTulipani-consumer-group
      max-poll-records: 100
      fetch-max-wait: 2000
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://cbq-hackathon.servicebus.windows.net/;SharedAccessKeyName=n;SharedAccessKey=BNCQDfe7PKmbM7quJjo2moDhHAp0HfyIp+AEhM5Omfo=;EntityPath=team6";
      security:
        protocol: SASL_SSL
  datasource:
    url: jdbc:mysql://root:gQ8vzSyBSk1C7qBlnAmuHoTr8O7mnbfE@mct5aa.stackhero-network.com/root?useSSL=true&requireSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: gQ8vzSyBSk1C7qBlnAmuHoTr8O7mnbfE
#    url: jdbc:mysql://localhost:3306/kojkukac
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: eKc92Bud
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Enable logging for H2 database (optional)
logging:
  level:
    com.h2database: debug

codebooq:
  api:
    bearer-token: 17d85969-69c0-4dd6-8a81-fb7dfc68c452
    url: https://hackathon.kojikukac.com/api/ParkingSpot
    timeout: 3